import { check, group } from "k6"
import { uuidv4, MaskinportenAccessTokenGenerator } from "../../commonImports.js"
import { SystemRegisterApiClient } from '../../clients/index.js'
import { CreateNewSystem, DeleteSystem, GetSystemRegisterRights } from '../../building_blocks/systemRegister/index.js';

function defaultObject() {
    const name = `NoeVisuelt${uuidv4()}`
    const allowedRedirectUrls = ["https://altinn.no"]
    const clientId = uuidv4()
    const vendorId = 312605031 // https://github.com/Altinn/altinn-authentication/blob/2b87e2eb6b11212c5aaf2032897bc9b8bc5e7519/test/Altinn.Platform.Authentication.SystemIntegrationTests/Resources/Testusers/testusers.at22.json
    const systemId = `${vendorId}_${name}`
    const description = {
        "en": "This is auto generated by an integration test. Some data is randomized, but some is not - like this description",
        "nb": "Integrasjonstest. Noe er randomisert her, men mye blir likt.",
        "nn": "integrasjonstest på nynorsk. Noe er randomisert her, men mye blir likt."
    }
    const rights = [
        {
            "resource": [
                {
                    "value": "authentication-e2e-test",
                    "id": "urn:altinn:resource"
                }
            ]
        },
        {
            "resource": [
                {
                    "value": "vegardtestressurs",
                    "id": "urn:altinn:resource"
                }
            ]
        }
    ]

    return [name, allowedRedirectUrls, clientId, vendorId, systemId, description, rights]
}
/*
export function teardown(data) {

}
*/
export default function () {
    const tokenGenerator
        = new MaskinportenAccessTokenGenerator()

    const systemRegisterClient
        = new SystemRegisterApiClient(__ENV.BASE_URL, tokenGenerator)

    // variables and whatnot
    const [name, allowedRedirectUrls, clientId, vendorId, systemId, description, rights] = defaultObject();


    group('System Register Rights Workflow', function () {
        console.log("CreateNewSystem")
        let res = CreateNewSystem(systemRegisterClient, vendorId, name, clientId, description, rights, allowedRedirectUrls)
        check(res, {
            'CreateNewSystem - Creating a new System returns an ID': (r) => {
                const jsonBody = JSON.parse(r);
                const re = /^[a-z\d\-]+$/
                return re.test(jsonBody);
            }
        });

        res = GetSystemRegisterRights(systemRegisterClient, systemId)
        check(res, {
            'GetSystemRegisterRights - Rights are correctly returned': (r) => {
                const jsonBody = JSON.parse(r);
                return Array.isArray(jsonBody) &&
                    jsonBody.length == 2;
            }
        });

        console.log("DeleteSystem")
        res = DeleteSystem(systemRegisterClient, systemId)
        check(res, {
            'DeleteSystem - Body contains succeeded: true': (r) => {
                const jsonBody = JSON.parse(r);
                return "succeeded" in jsonBody &&
                    jsonBody.succeeded == true;
            }
        });
    });
}
